name: Build with custom Vulkan
run-name: Build with ${{inputs.vulkan}}
on:
  workflow_dispatch:
    inputs:
      vulkan:
        description: Vulkan revision
        required: true
        default: YaaZ/Vulkan-Hpp#main
        type: string
  workflow_call:
    inputs:
      vulkan:
        required: true
        type: string
jobs:
  build:
    name: ${{matrix.env.os}} ${{matrix.env.name || matrix.env.c}} ${{matrix.env.modules && 'cppm'}}
    env:
      compiler: ${{matrix.env.name || matrix.env.c}}
      modules: ${{matrix.env.modules}}
    runs-on: ${{matrix.env.os}}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        env: [
          { os: macos-26, cxx: clang++, name: apple-clang },
          { os: macos-26, cxx: '$(brew --prefix llvm@20)/bin/clang++', name: clang, extra_flags: '-DCMAKE_OSX_SYSROOT=macosx' },
          { os: macos-26, cxx: '$(brew --prefix llvm@20)/bin/clang++', name: clang, extra_flags: '-DCMAKE_OSX_SYSROOT=macosx', modules: true },
          { os: macos-26, cxx: g++-13, c: gcc-13 },
          { os: macos-26, cxx: g++-14, c: gcc-14, cxx_flags: '-D__STDC_WANT_LIB_EXT1__=0' },
          { os: macos-26, cxx: g++-15, c: gcc-15, cxx_flags: '-D__STDC_WANT_LIB_EXT1__=0' },
          { os: macos-26, cxx: g++-15, c: gcc-15, cxx_flags: '-D__STDC_WANT_LIB_EXT1__=0', modules: true, extra_flags: '-DVMA_HPP_SAMPLES_BUILD=OFF' }, # TODO Build samples when GCC stops failing with ICE
          { os: ubuntu-24.04, cxx: clang++-16, c: clang-16 },
          { os: ubuntu-24.04, cxx: clang++-17, c: clang-17 },
          { os: ubuntu-24.04, cxx: clang++-18, c: clang-18 },
          { os: ubuntu-26.04, cxx: clang++-20, c: clang-20 },
          { os: ubuntu-26.04, cxx: clang++-21, c: clang-21 },
          { os: ubuntu-26.04, cxx: clang++-22, c: clang-22 },
          { os: ubuntu-26.04, cxx: clang++-20, c: clang-20, modules: true },
          { os: ubuntu-26.04, cxx: clang++-21, c: clang-21, modules: true },
          { os: ubuntu-26.04, cxx: clang++-22, c: clang-22, modules: true },
          { os: ubuntu-24.04, cxx: clang++-16, c: clang-16, name: clang-16-libc++, cxx_flags: '-stdlib=libc++', linker_flags: '-stdlib=libc++ -lc++abi' },
          { os: ubuntu-24.04, cxx: clang++-17, c: clang-17, name: clang-17-libc++, cxx_flags: '-stdlib=libc++', linker_flags: '-stdlib=libc++ -lc++abi' },
          { os: ubuntu-24.04, cxx: clang++-18, c: clang-18, name: clang-18-libc++, cxx_flags: '-stdlib=libc++', linker_flags: '-stdlib=libc++ -lc++abi' },
          { os: ubuntu-26.04, cxx: clang++-20, c: clang-20, name: clang-20-libc++, cxx_flags: '-stdlib=libc++', linker_flags: '-stdlib=libc++ -lc++abi' },
          { os: ubuntu-26.04, cxx: clang++-21, c: clang-21, name: clang-21-libc++, cxx_flags: '-stdlib=libc++', linker_flags: '-stdlib=libc++ -lc++abi' },
          { os: ubuntu-26.04, cxx: clang++-22, c: clang-22, name: clang-22-libc++, cxx_flags: '-stdlib=libc++', linker_flags: '-stdlib=libc++ -lc++abi' },
          { os: ubuntu-24.04, cxx: clang++-18, c: clang-18, name: clang-18-libc++, cxx_flags: '-stdlib=libc++', linker_flags: '-stdlib=libc++ -lc++abi', modules: true },
          { os: ubuntu-26.04, cxx: clang++-20, c: clang-20, name: clang-20-libc++, cxx_flags: '-stdlib=libc++', linker_flags: '-stdlib=libc++ -lc++abi', modules: true },
          { os: ubuntu-26.04, cxx: clang++-21, c: clang-21, name: clang-21-libc++, cxx_flags: '-stdlib=libc++', linker_flags: '-stdlib=libc++ -lc++abi', modules: true },
          { os: ubuntu-26.04, cxx: clang++-22, c: clang-22, name: clang-22-libc++, cxx_flags: '-stdlib=libc++', linker_flags: '-stdlib=libc++ -lc++abi', modules: true },
          { os: ubuntu-24.04, cxx: g++-12, c: gcc-12 },
          { os: ubuntu-24.04, cxx: g++-13, c: gcc-13 },
          { os: ubuntu-24.04, cxx: g++-14, c: gcc-14 },
          { os: ubuntu-26.04, cxx: g++-15, c: gcc-15 },
          { os: ubuntu-26.04, cxx: g++-15, c: gcc-15, modules: true, extra_flags: '-DVMA_HPP_SAMPLES_BUILD=OFF' }, # TODO Build samples when GCC stops failing with ICE
          { os: windows-2025, name: msvc, cxx_flags: '//EHsc' },
          { os: windows-2025, name: msvc, cxx_flags: '//EHsc', modules: true },
          { os: windows-2025, cxx: clang-cl, c: clang-cl, cxx_flags: '/EHsc' },
          { os: windows-2025, cxx: c++, c: cc, name: gcc },
        ]
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
        with:
          submodules: true
      - name: Setup CMake and Ninja
        if: matrix.env.modules
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: 4.1.2
          ninjaVersion: latest
      - name: Setup MSVC
        if: contains(matrix.env.os, 'windows') && matrix.env.name == 'msvc'
        uses: TheMrMilchmann/setup-msvc-dev@v4
        with:
          arch: x64
      - name: Setup libc++
        if: contains(matrix.env.os, 'ubuntu') && contains(matrix.env.name, 'libc++')
        run: |
          N=$(${{matrix.env.cxx}} -dumpversion | cut -d. -f1)
          sudo apt install libc++-$N-dev libc++abi-$N-dev
      - name: Fix 'import std'
        if: contains(matrix.env.os, 'ubuntu') && contains(matrix.env.name, 'libc++') && matrix.env.modules
        run: |
          LLVM=$(realpath "$(dirname "$(readlink -f "$(which ${{matrix.env.cxx}})")")/..")
          JSON=$(readlink -f "$(${{matrix.env.cxx}} -stdlib=libc++ -print-file-name=libc++.modules.json)")
          SRC=$(dirname "$JSON")/$(grep -o '"source-path": *"[^"]*std.cppm"' "$JSON" | sed 's/.*"\(.*\)"/\1/')
          if [[ ! -f "$SRC" ]]; then
            sudo sed -i "s|\"\.\./share/|\"$LLVM/share/|g" "$JSON"
            echo "Patched $JSON"
          fi
      - name: Fix 'import std'
        if: contains(matrix.env.os, 'macos') && contains(matrix.env.name, 'clang') && matrix.env.modules
        run: | # https://gitlab.kitware.com/cmake/cmake/-/issues/25965#note_1523575
          LLVM=$(dirname $(dirname ${{matrix.env.cxx}}))
          sed "s|\.\./\.\./share|$LLVM/share|g" $LLVM/lib/c++/libc++.modules.json > $LLVM/lib/libc++.modules.json
      - name: Setup build environment
        run: |
          IFS='#' read -r -a VULKAN <<< '${{inputs.vulkan}}'
          FLAGS=(--no-checkout --shallow-exclude=v1.4.326 --branch main)
          [[ ${VULKAN[1]} ]] && FLAGS=(--depth 1 --branch ${VULKAN[1]})
          git clone --single-branch ${FLAGS[@]} ${VULKAN[0]} vulkan || \
          git clone --single-branch ${FLAGS[@]} https://github.com/${VULKAN[0]}.git vulkan
          (cd vulkan && git submodule update --init --depth 1 Vulkan-Headers || true)
          echo "vk=${VULKAN[1]}" >> $GITHUB_ENV
          
          cat > build <<'EOF'
          #!/usr/bin/env bash
          set -eo pipefail
          (cd vulkan && git checkout -q -f $1)
          shift
          CXX_FLAGS=(
              ${{(contains(env.compiler, 'clang') || contains(env.compiler, 'gcc')) && '-Wno-nullability-completeness -Wno-deprecated-declarations' || ''}}
              ${{matrix.env.cxx_flags || ''}}
          )
          CXX_FLAGS="${CXX_FLAGS[@]} $@"
          FLAGS=(
              -B cmake-build -G Ninja --fresh
              -DVMA_HPP_GENERATOR_BUILD=OFF
              -DVMA_HPP_RUN_GENERATOR=OFF
              -DCMAKE_BUILD_TYPE=Release
              -DFETCHCONTENT_SOURCE_DIR_VULKAN=vulkan
              -DVULKAN_HEADERS_ENABLE_MODULE=${{matrix.env.modules && 'ON' || 'OFF'}}
              -DVULKAN_HPP_BUILD_CXX_MODULE=${{matrix.env.modules && 'ON' || 'OFF'}}
              ${{matrix.env.modules && '-DCMAKE_EXPERIMENTAL_CXX_IMPORT_STD=d0edc3af-4c50-42ea-a356-e2862fe7a444' || ''}}
              ${{matrix.env.cxx && format('-DCMAKE_CXX_COMPILER={0}', matrix.env.cxx)}}
              ${{matrix.env.c && format('-DCMAKE_C_COMPILER={0}', matrix.env.c)}}
              ${{matrix.env.linker_flags && format('-DCMAKE_EXE_LINKER_FLAGS=''{0}''', matrix.env.linker_flags)}}
              ${{matrix.env.extra_flags || ''}}
              -DCMAKE_CXX_FLAGS="$CXX_FLAGS"
          )
          RESULT=0
          for STANDARD in ${{!matrix.env.modules && '11 14 17 20' || ''}} 23; do
            ${{env.compiler == 'clang-17' && '[[ $STANDARD == 23 ]] && continue # clang-17 + c++23 is excluded.' || ''}}
            echo "::group::Build with c++$STANDARD"
            rm -r cmake-build &> /dev/null || true
            cmake "${FLAGS[@]}" -DCMAKE_CXX_STANDARD=$STANDARD || { echo "::error::CMake failed with c++$STANDARD $@"; RESULT=1; }
            cmake --build cmake-build || { echo "::error::Build failed with c++$STANDARD $@"; RESULT=1; }
            ${{matrix.env.modules && 'ls cmake-build/include/CMakeFiles | grep VulkanMemoryAllocator-HppModule &> /dev/null || \'}}
            ${{matrix.env.modules && '{ echo "::error::VulkanMemoryAllocator-HppModule was not built for c++$STANDARD $@"; RESULT=1; }'}}
            echo "::endgroup::"
          done
          exit $RESULT
          EOF
          chmod +x build
          echo . >> $GITHUB_PATH
      - if: ${{!cancelled()}}
        run: build ${{env.vk || env.modules && 'v1.4.344' || 'v1.4.327'}}
      - if: ${{!cancelled()}}
        run: build ${{env.vk || env.modules && 'v1.4.344' || 'v1.4.327'}} -DVULKAN_HPP_NO_EXCEPTIONS
      - if: ${{!cancelled()}}
        run: build ${{env.vk || env.modules && 'v1.4.344' || 'v1.4.327'}} -DVULKAN_HPP_NO_SMART_HANDLE
      - if: ${{!cancelled()}}
        run: build ${{env.vk || env.modules && 'v1.4.344' || 'v1.4.327'}} -DVULKAN_HPP_USE_REFLECT -DVULKAN_HPP_HANDLES_MOVE_EXCHANGE
      - if: ${{!cancelled()}}
        run: build ${{env.vk || env.modules && 'v1.4.345' || 'v1.4.345'}} -DVULKAN_HPP_TYPESAFE_CONVERSION=0
      - if: ${{!cancelled() && !env.modules}} # Build modules when https://github.com/KhronosGroup/Vulkan-Hpp/pull/2716 arrives from upstream.
        run: build ${{env.vk || env.modules && '[broken]' || 'v1.4.348'}} -DVULKAN_HPP_NO_EXCEPTIONS -DVULKAN_HPP_USE_STD_EXPECTED
